#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello:
     path: /hello
     controller: App\Controller\HelloController::index

helloName:
     path: /hello-name/{name}
     controller: App\Controller\HelloController::helloName